# Generated by Django 4.2.6 on 2023-11-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappF23', '0007_remove_course_student_course_interested_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='interested_students',
            new_name='students',
        ),
    ]
